name: full

on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        nodejs-version: [16.19.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run Storybook build
        run: npm run build-storybook

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ui-library
          directory: /storybook-static
          branch: develop
