name: full

on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        nodejs-version: [16.19.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: Cache dependencies
        uses: actions/cache@v3.3.1
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        run: npm ci

      - name: Run Storybook build
        run: npm run build-storybook

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ui-library
          directory: storybook-static
          branch: develop

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3.3.1
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/package-lock.json')}}

      - name: Use Node.js 16.19.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - run: npm run semantic-release
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
